/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.RegistrarRole;

import UserInterface.WorkAreas.RegistrarRole.CourseOfferingManagement.ManageCourseOfferingsJPanel;
import UserInterface.WorkAreas.RegistrarRole.ProfileManagement.RegistrarProfileJPanel;
import UserInterface.WorkAreas.RegistrarRole.ReportsAnalytics.InstitutionalReportsJPanel;
import UserInterface.WorkAreas.RegistrarRole.StudentRegistrationManagement.ManageStudentRegistrationJPanel;
import UserInterface.WorkAreas.RegistrarRole.TuitionFinancial.TuitionManagementJPanel;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author chris
 */
public class RegistrarWorkAreaJPanel extends javax.swing.JPanel {

    private Department department;
    private JPanel CardSequencePanel;
    private UserAccount useraccount;

    /**
     * Creates new form RegistrarWorkAreaJPanel
     */
    public RegistrarWorkAreaJPanel(Department dept, UserAccount useracc, JPanel cardPanel) {
        this.department = dept;
        this.useraccount = useracc;
        this.CardSequencePanel = cardPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCourseOfferingManagement = new javax.swing.JButton();
        btnTuition = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnStudentRegistration = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnProfile = new javax.swing.JButton();

        btnCourseOfferingManagement.setBackground(new java.awt.Color(102, 153, 255));
        btnCourseOfferingManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseOfferingManagement.setText("Course Offering Management");
        btnCourseOfferingManagement.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCourseOfferingManagement.setMaximumSize(new java.awt.Dimension(200, 40));
        btnCourseOfferingManagement.setMinimumSize(new java.awt.Dimension(20, 23));
        btnCourseOfferingManagement.setPreferredSize(new java.awt.Dimension(240, 30));
        btnCourseOfferingManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseOfferingManagementIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnTuition.setBackground(new java.awt.Color(102, 153, 255));
        btnTuition.setForeground(new java.awt.Color(255, 255, 255));
        btnTuition.setText("Tuition & Financial");
        btnTuition.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTuition.setMaximumSize(new java.awt.Dimension(200, 40));
        btnTuition.setMinimumSize(new java.awt.Dimension(20, 20));
        btnTuition.setPreferredSize(new java.awt.Dimension(240, 25));
        btnTuition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuitionActionPerformed(evt);
            }
        });

        btnReports.setBackground(new java.awt.Color(102, 153, 255));
        btnReports.setForeground(new java.awt.Color(255, 255, 255));
        btnReports.setText("Reports & Analytics");
        btnReports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReports.setMaximumSize(new java.awt.Dimension(200, 40));
        btnReports.setMinimumSize(new java.awt.Dimension(20, 20));
        btnReports.setPreferredSize(new java.awt.Dimension(240, 25));
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        btnStudentRegistration.setBackground(new java.awt.Color(102, 153, 255));
        btnStudentRegistration.setForeground(new java.awt.Color(255, 255, 255));
        btnStudentRegistration.setText("Student Registration");
        btnStudentRegistration.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStudentRegistration.setMaximumSize(new java.awt.Dimension(200, 40));
        btnStudentRegistration.setMinimumSize(new java.awt.Dimension(20, 20));
        btnStudentRegistration.setPreferredSize(new java.awt.Dimension(240, 25));
        btnStudentRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentRegistrationActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setText("Registrar Portal");

        btnProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnProfile.setText("My Profile");
        btnProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProfile.setMaximumSize(new java.awt.Dimension(200, 40));
        btnProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnProfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnCourseOfferingManagement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(btnTuition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnStudentRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(590, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblTitle)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourseOfferingManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudentRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTuition, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseOfferingManagementIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseOfferingManagementIdentifyResourceAssetsActionPerformed
        ManageCourseOfferingsJPanel managePanel = new ManageCourseOfferingsJPanel(department, CardSequencePanel);
        CardSequencePanel.add("ManageCourseOfferingsJPanel", managePanel);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.next(CardSequencePanel);
    }//GEN-LAST:event_btnCourseOfferingManagementIdentifyResourceAssetsActionPerformed

    private void btnTuitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuitionActionPerformed
        // TODO add your handling code here:
        TuitionManagementJPanel tuitionPanel = new TuitionManagementJPanel(department, CardSequencePanel);
        CardSequencePanel.add("TuitionManagementJPanel", tuitionPanel);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.next(CardSequencePanel);
    }//GEN-LAST:event_btnTuitionActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
        InstitutionalReportsJPanel reportPanel = new InstitutionalReportsJPanel(department, CardSequencePanel);
        CardSequencePanel.add("InstitutionalReportsJPanel", reportPanel);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.next(CardSequencePanel);
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnStudentRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentRegistrationActionPerformed
        // TODO add your handling code here:
        ManageStudentRegistrationJPanel studentPanel = new ManageStudentRegistrationJPanel(department, CardSequencePanel);
        CardSequencePanel.add("ManageStudentRegistrationJPanel", studentPanel);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.next(CardSequencePanel);
    }//GEN-LAST:event_btnStudentRegistrationActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        RegistrarProfileJPanel profilePanel = new RegistrarProfileJPanel(department, CardSequencePanel);
        CardSequencePanel.add("RegistrarProfileJPanel", profilePanel);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.next(CardSequencePanel);
    }//GEN-LAST:event_btnProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseOfferingManagement;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnStudentRegistration;
    private javax.swing.JButton btnTuition;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
